version: '3.8'

services:
  bot:
    build: .
    container_name: detect_fake_img_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
